$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.6.0/schemas/v1/install.json
artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.11.6
    requires:
      - "22"
  "@daiyam/artifact-lang-ts":
    version: 0.8.2
  "@daiyam/artifact-npm":
    version: 0.8.5
  "@daiyam/artifact-npm-zokugun":
    version: 0.3.2
  "@daiyam/artifact-npm-ts":
    version: 0.6.1
  "@daiyam/artifact-npm-cli-ts":
    version: 0.8.3
  "@daiyam/artifact-gh-issuehub":
    version: 0.6.3
